# Generated by Django 2.2.2 on 2019-06-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssd', models.DateField()),
                ('sdd', models.DateField()),
                ('sqd', models.DateField()),
                ('hol', models.IntegerField()),
            ],
            options={
                'db_table': 'productcon',
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('roles', models.CharField(choices=[('dev', 'Developer'), ('man', 'Manager'), ('cto', 'CTO')], default='Role', max_length=3)),
                ('skills', models.CharField(choices=[('html', 'HTML'), ('php', 'PHP'), ('java', 'JAVA'), ('qa', 'QA')], default='Skill', max_length=4)),
            ],
            options={
                'db_table': 'reg',
            },
        ),
    ]
