# Generated by Django 2.2 on 2019-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg',
            name='actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
