# Generated by Django 2.2 on 2019-07-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0002_prg_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg',
            name='actual',
        ),
    ]
