# Generated by Django 2.2 on 2019-07-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0003_remove_prg_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hactual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='jactual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='pactual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='qactual',
            field=models.IntegerField(default=0),
        ),
    ]
