# Generated by Django 2.2.2 on 2019-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='roles',
            field=models.CharField(choices=[('dev', 'Developer'), ('man', 'Manager')], default='Role', max_length=3),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
