# Generated by Django 2.2.2 on 2019-06-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0004_auto_20190625_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='uname',
            new_name='username',
        ),
    ]
