# Generated by Django 2.2.2 on 2019-06-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0005_auto_20190625_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
