# Generated by Django 2.2 on 2019-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
