# Generated by Django 2.2.2 on 2019-06-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arc', '0006_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roles', models.CharField(choices=[('dev', 'Developer'), ('man', 'Manager')], default='Role', max_length=3)),
                ('skills', models.CharField(choices=[('html', 'HTML'), ('php', 'PHP'), ('java', 'JAVA'), ('qa', 'QA')], default='Skill', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
