# Generated by Django 2.2 on 2019-07-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0006_product_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg',
            name='edate',
        ),
    ]
