# Generated by Django 2.2.2 on 2019-06-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0007_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='prod',
        ),
    ]
