# Generated by Django 2.2 on 2019-07-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0007_remove_prg_edate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg',
            name='days',
        ),
    ]
