# Generated by Django 2.2.2 on 2019-06-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0008_auto_20190625_1003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
