# Generated by Django 2.2 on 2019-07-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0008_remove_prg_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='hstat',
        ),
        migrations.RemoveField(
            model_name='story',
            name='jstat',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pstat',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qstat',
        ),
    ]
