# Generated by Django 2.2 on 2019-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0009_auto_20190716_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='ostatus',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
