# Generated by Django 2.2.2 on 2019-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0009_auto_20190625_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hol',
            field=models.IntegerField(default=0),
        ),
    ]
