# Generated by Django 2.2.2 on 2019-06-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0010_auto_20190625_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sdd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sqd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ssd',
        ),
    ]
