# Generated by Django 2.2 on 2019-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0011_cregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='cregister',
            name='roles',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
