# Generated by Django 2.2.2 on 2019-06-25 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0011_auto_20190625_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sdd',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='sqd',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
