# Generated by Django 2.2.2 on 2019-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0012_auto_20190625_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
    ]
