# Generated by Django 2.2 on 2019-07-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0012_cregister_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='abhtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='abjava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='abphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='abqa',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dhtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='djava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dqa',
        ),
        migrations.RemoveField(
            model_name='register',
            name='planned',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sphtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='spjava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='spphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='spqa',
        ),
        migrations.RemoveField(
            model_name='register',
            name='unplanned',
        ),
        migrations.RemoveField(
            model_name='register',
            name='vfhtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='vfjava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='vfphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='vfqa',
        ),
    ]
