# Generated by Django 2.2.2 on 2019-06-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0013_product_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='prod',
        ),
    ]
