# Generated by Django 2.2 on 2019-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0014_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='ostatus',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
