# Generated by Django 2.2.2 on 2019-06-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0014_auto_20190625_1218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
