# Generated by Django 2.2.2 on 2019-06-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0015_auto_20190625_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hol',
            new_name='holidays',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sdd',
            new_name='sprint_dev_end_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sqd',
            new_name='sprint_qa_end_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ssd',
            new_name='sprint_start_date',
        ),
    ]
