# Generated by Django 2.2 on 2019-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0015_auto_20190717_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='ostatus',
            field=models.CharField(max_length=20),
        ),
    ]
