# Generated by Django 2.1.7 on 2019-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0016_auto_20190625_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('jira', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
    ]
