# Generated by Django 2.1.7 on 2019-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0017_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(),
        ),
    ]
