# Generated by Django 2.1.7 on 2019-06-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0018_auto_20190626_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='point',
        ),
    ]
