# Generated by Django 2.2 on 2019-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0018_auto_20190717_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='hactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='story',
            name='jactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='story',
            name='pactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='story',
            name='qactual',
            field=models.FloatField(default=0.0),
        ),
    ]
