# Generated by Django 2.2 on 2019-07-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0019_auto_20190717_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='hactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='jactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qactual',
        ),
    ]
