# Generated by Django 2.2 on 2019-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0020_auto_20190717_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='jactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='pactual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='qactual',
            field=models.FloatField(default=0.0),
        ),
    ]
