# Generated by Django 2.1.7 on 2019-06-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0021_remove_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
