# Generated by Django 2.2 on 2019-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0022_prg_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='dev_java',
            field=models.TextField(max_length=10000),
        ),
    ]
