# Generated by Django 2.1.7 on 2019-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0022_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sprint_name',
            field=models.CharField(default=None, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
