# Generated by Django 2.1.7 on 2019-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0023_story_sprint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprint_name',
            field=models.CharField(max_length=100),
        ),
    ]
