# Generated by Django 2.2 on 2019-07-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0023_auto_20190722_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comments',
            field=models.TextField(default=None, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='dev_java',
            field=models.CharField(max_length=200),
        ),
    ]
