# Generated by Django 2.1.7 on 2019-06-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0024_auto_20190626_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='sprint_name',
        ),
    ]
