# Generated by Django 2.1.7 on 2019-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0025_remove_story_sprint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='sprint_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
