# Generated by Django 2.2 on 2019-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0025_auto_20190723_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='hleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='jleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qleft',
        ),
        migrations.AddField(
            model_name='prg',
            name='left',
            field=models.FloatField(default=0.0),
        ),
    ]
