# Generated by Django 2.1.7 on 2019-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0026_story_sprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprint_id',
            field=models.IntegerField(default=0),
        ),
    ]
