# Generated by Django 2.2 on 2019-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0026_auto_20190723_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hleft',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='jleft',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='pleft',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='qleft',
            field=models.FloatField(default=0.0),
        ),
    ]
