# Generated by Django 2.1.7 on 2019-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0027_auto_20190626_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sprint_id',
            field=models.IntegerField(),
        ),
    ]
