# Generated by Django 2.2 on 2019-07-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0027_auto_20190723_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg',
            name='cl',
            field=models.FloatField(default=0.0),
        ),
    ]
