# Generated by Django 2.1.7 on 2019-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0028_auto_20190626_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
