# Generated by Django 2.2 on 2019-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0028_prg_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='devs',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
