# Generated by Django 2.1.7 on 2019-06-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0029_auto_20190626_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(),
        ),
    ]
