# Generated by Django 2.1.7 on 2019-06-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0030_auto_20190626_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dev_working',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qa_working',
        ),
    ]
