# Generated by Django 2.1.7 on 2019-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0031_auto_20190626_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='skills',
        ),
        migrations.AddField(
            model_name='register',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='java',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='php',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='qa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='roles',
            field=models.CharField(choices=[('dev', 'Developer'), ('man', 'Manager')], default='Roles', max_length=4),
        ),
    ]
