# Generated by Django 2.1.7 on 2019-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0032_auto_20190626_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
