# Generated by Django 2.1.7 on 2019-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0033_auto_20190626_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(default=0),
        ),
    ]
