# Generated by Django 2.1.7 on 2019-06-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0036_auto_20190626_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dev_working',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qa_working',
        ),
    ]
