# Generated by Django 2.2 on 2019-07-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0042_auto_20190725_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pic',
        ),
    ]
