# Generated by Django 2.1.7 on 2019-06-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0042_auto_20190626_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dev_working',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qa_working',
        ),
    ]
