# Generated by Django 2.2 on 2019-07-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0044_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
