# Generated by Django 2.1.7 on 2019-06-26 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0044_auto_20190626_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sprint_dev_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='sprint_qa_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='sprint_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
