# Generated by Django 2.2 on 2019-07-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0045_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='empid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
