# Generated by Django 2.1.7 on 2019-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0045_auto_20190626_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='check',
            field=models.BooleanField(default='False'),
        ),
    ]
