# Generated by Django 2.1.7 on 2019-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0046_story_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='check',
            field=models.BooleanField(default='True'),
        ),
    ]
