# Generated by Django 2.2 on 2019-07-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0047_auto_20190731_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
