# Generated by Django 2.1.7 on 2019-06-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0048_remove_story_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sprint_start_date',
            field=models.DateField(),
        ),
    ]
