# Generated by Django 2.2 on 2019-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0048_auto_20190731_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sprint_dev_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sprint_qa_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sprint_start_date',
            field=models.DateField(),
        ),
    ]
