# Generated by Django 2.1.7 on 2019-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0049_auto_20190627_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sprint_start_date',
            field=models.CharField(max_length=10),
        ),
    ]
