# Generated by Django 2.1.7 on 2019-06-27 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0050_auto_20190627_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sprint_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
