# Generated by Django 2.1.7 on 2019-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0051_auto_20190627_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
