# Generated by Django 2.1.7 on 2019-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0052_auto_20190627_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dev_working',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='qa_working',
            field=models.IntegerField(default=0),
        ),
    ]
