# Generated by Django 2.1.7 on 2019-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0053_auto_20190627_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='vfhtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='vfjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='vfphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='vfqa',
            field=models.IntegerField(default=0),
        ),
    ]
