# Generated by Django 2.2 on 2019-08-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0053_auto_20190807_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='sprint',
        ),
    ]
