# Generated by Django 2.2 on 2019-08-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0054_auto_20190807_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cregister',
            new_name='user_sprint_details',
        ),
    ]
