# Generated by Django 2.1.7 on 2019-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0054_auto_20190628_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='bandwidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vfh', models.IntegerField(default=0)),
                ('vfp', models.IntegerField(default=0)),
                ('vfj', models.IntegerField(default=0)),
                ('vfq', models.IntegerField(default=0)),
            ],
        ),
    ]
