# Generated by Django 2.2 on 2019-08-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0055_auto_20190807_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_sprint_details',
            new_name='user_sprint_detail',
        ),
    ]
