# Generated by Django 2.1.7 on 2019-06-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0055_bandwidth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bandwidth',
        ),
    ]
