# Generated by Django 2.2 on 2019-08-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0056_auto_20190807_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prg',
            new_name='progress',
        ),
    ]
