# Generated by Django 2.1.7 on 2019-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0056_delete_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='vfhtml',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='vfjava',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='vfphp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='vfqa',
            field=models.FloatField(default=0),
        ),
    ]
