# Generated by Django 2.1.7 on 2019-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0057_auto_20190628_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='abhtml',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='abjava',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='abphp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='abqa',
            field=models.FloatField(default=0),
        ),
    ]
