# Generated by Django 2.2 on 2019-08-07 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arc', '0057_auto_20190807_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='user_detail',
        ),
    ]
