# Generated by Django 2.1.7 on 2019-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0058_auto_20190628_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='abhtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='abjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='abphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='abqa',
            field=models.IntegerField(default=0),
        ),
    ]
