# Generated by Django 2.2 on 2019-08-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0058_auto_20190807_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='story_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField()),
                ('dev_java', models.CharField(max_length=200)),
                ('dev_php', models.CharField(max_length=200)),
                ('dev_html', models.CharField(max_length=200)),
                ('dev_qa', models.CharField(max_length=200)),
                ('javas', models.IntegerField(default=0)),
                ('phps', models.IntegerField(default=0)),
                ('htmls', models.IntegerField(default=0)),
                ('qas', models.IntegerField(default=0)),
                ('ostatus', models.CharField(max_length=20)),
                ('comments', models.TextField(max_length=10000)),
                ('jactual', models.FloatField(default=0.0)),
                ('pactual', models.FloatField(default=0.0)),
                ('hactual', models.FloatField(default=0.0)),
                ('qactual', models.FloatField(default=0.0)),
                ('jleft', models.FloatField(default=0.0)),
                ('pleft', models.FloatField(default=0.0)),
                ('hleft', models.FloatField(default=0.0)),
                ('qleft', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='story',
            name='dev_html',
        ),
        migrations.RemoveField(
            model_name='story',
            name='dev_java',
        ),
        migrations.RemoveField(
            model_name='story',
            name='dev_php',
        ),
        migrations.RemoveField(
            model_name='story',
            name='dev_qa',
        ),
        migrations.RemoveField(
            model_name='story',
            name='hactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='hleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='htmls',
        ),
        migrations.RemoveField(
            model_name='story',
            name='jactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='javas',
        ),
        migrations.RemoveField(
            model_name='story',
            name='jleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='ostatus',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='phps',
        ),
        migrations.RemoveField(
            model_name='story',
            name='pleft',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qactual',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qas',
        ),
        migrations.RemoveField(
            model_name='story',
            name='qleft',
        ),
    ]
