# Generated by Django 2.2 on 2019-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0059_auto_20190812_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_details',
            name='sprint_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
