# Generated by Django 2.1.7 on 2019-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0060_register_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='sphtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='spjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='spphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='spqa',
            field=models.IntegerField(default=0),
        ),
    ]
