# Generated by Django 2.2 on 2019-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0060_story_details_sprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_details',
            name='jira',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
