# Generated by Django 2.2 on 2019-08-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0061_story_details_jira'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('creator', models.CharField(max_length=150)),
                ('devs', models.CharField(max_length=1000)),
                ('mans', models.CharField(max_length=1000)),
            ],
        ),
    ]
