# Generated by Django 2.1.7 on 2019-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0061_auto_20190628_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='sumhtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='sumjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='sumphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='sumqa',
            field=models.IntegerField(default=0),
        ),
    ]
