# Generated by Django 2.1.7 on 2019-06-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0062_auto_20190628_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='sumhtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sumjava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sumphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sumqa',
        ),
    ]
