# Generated by Django 2.2 on 2019-08-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0062_project_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='devs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mans',
        ),
    ]
