# Generated by Django 2.1.7 on 2019-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0063_auto_20190628_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumjava', models.IntegerField(default=0)),
                ('sumphp', models.IntegerField(default=0)),
                ('sumhtml', models.IntegerField(default=0)),
                ('sumqa', models.IntegerField(default=0)),
            ],
        ),
    ]
