# Generated by Django 2.1.7 on 2019-06-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0064_totalpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='totalpoints',
        ),
    ]
