# Generated by Django 2.2 on 2019-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0065_auto_20190813_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_of_comment',
            field=models.CharField(blank='False', max_length=50),
        ),
    ]
