# Generated by Django 2.1.7 on 2019-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0065_delete_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='asphtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='aspjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='aspphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='aspqa',
            field=models.IntegerField(default=0),
        ),
    ]
