# Generated by Django 2.2 on 2019-08-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0066_comments_date_of_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_of_comment',
        ),
    ]
