# Generated by Django 2.1.7 on 2019-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0066_auto_20190628_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dhtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='djava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='dphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='dqa',
            field=models.IntegerField(default=0),
        ),
    ]
