# Generated by Django 2.1.7 on 2019-06-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0067_auto_20190629_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='dev_html',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='dev_java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='dev_php',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='dev_qa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='shtml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='sjava',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='sphp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='sqa',
            field=models.IntegerField(default=0),
        ),
    ]
