# Generated by Django 2.2 on 2019-08-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0067_remove_comments_date_of_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='cl',
            new_name='calculated_left',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='dname',
            new_name='dev_name',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='jd',
            new_name='jira_id',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='s_id',
            new_name='story_id',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='sdate',
            new_name='work_date',
        ),
    ]
