# Generated by Django 2.1.7 on 2019-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0068_auto_20190629_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='shtml',
            new_name='htmls',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='sjava',
            new_name='javas',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='sphp',
            new_name='phps',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='sqa',
            new_name='qas',
        ),
    ]
