# Generated by Django 2.1.7 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0069_auto_20190629_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='dev_html',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='dev_java',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='dev_php',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='dev_qa',
            field=models.CharField(max_length=200),
        ),
    ]
