# Generated by Django 2.2 on 2019-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0069_auto_20190813_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story_details',
            old_name='htmls',
            new_name='assigned_html_points',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='javas',
            new_name='assigned_java_points',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='phps',
            new_name='assigned_php_points',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='qas',
            new_name='assigned_qa_points',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='hactual',
            new_name='html_points_done',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='hleft',
            new_name='html_points_left',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='jactual',
            new_name='java_points_done',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='jleft',
            new_name='java_points_left',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='pactual',
            new_name='php_points_done',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='pleft',
            new_name='php_points_left',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='qactual',
            new_name='qa_points_done',
        ),
        migrations.RenameField(
            model_name='story_details',
            old_name='qleft',
            new_name='qa_points_left',
        ),
    ]
