# Generated by Django 2.2 on 2019-08-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0070_auto_20190813_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_details',
            name='comments',
        ),
    ]
