# Generated by Django 2.1.7 on 2019-06-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0070_auto_20190629_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='asphtml',
        ),
        migrations.RemoveField(
            model_name='register',
            name='aspjava',
        ),
        migrations.RemoveField(
            model_name='register',
            name='aspphp',
        ),
        migrations.RemoveField(
            model_name='register',
            name='aspqa',
        ),
    ]
