# Generated by Django 2.1.7 on 2019-06-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0071_auto_20190630_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='spr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_id', models.IntegerField()),
                ('sjava', models.IntegerField(default=0)),
                ('sphp', models.IntegerField(default=0)),
                ('shtml', models.IntegerField(default=0)),
                ('sqa', models.IntegerField(default=0)),
            ],
        ),
    ]
