# Generated by Django 2.1.7 on 2019-06-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0072_spr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spr',
        ),
    ]
