# Generated by Django 2.2 on 2019-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0072_auto_20190813_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='brief_description',
            field=models.TextField(max_length=2000),
        ),
    ]
