# Generated by Django 2.2 on 2019-08-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0073_auto_20190813_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_details',
            name='ostatus',
        ),
    ]
