# Generated by Django 2.1.7 on 2019-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0073_delete_spr'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hstat',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='jstat',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='pstat',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='qstat',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
