# Generated by Django 2.2 on 2019-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0075_auto_20190814_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
    ]
