# Generated by Django 2.2 on 2019-08-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0076_user_detail_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
