# Generated by Django 2.1.7 on 2019-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0077_auto_20190702_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
        migrations.AlterField(
            model_name='story',
            name='hstat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='jstat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='pstat',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='qstat',
            field=models.CharField(max_length=10),
        ),
    ]
