# Generated by Django 2.2 on 2019-08-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0077_remove_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
