# Generated by Django 2.2 on 2019-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0078_comments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='profile',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
    ]
