# Generated by Django 2.1.7 on 2019-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0078_auto_20190702_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='hstat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='jstat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='pstat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='qstat',
            field=models.CharField(max_length=20),
        ),
    ]
