# Generated by Django 2.2 on 2019-08-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0079_user_detail_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='profile',
        ),
    ]
