# Generated by Django 2.1.7 on 2019-07-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0079_auto_20190702_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('l', 'Live'), ('ip', 'In Progress'), ('hd', 'HTML Done'), ('pd', 'PHP Done'), ('ad', 'API Done'), ('qa', 'QA'), ('pd', 'Pending Development'), ('bd', 'Blocked'), ('ba', 'Blocked on API'), ('bh', 'Blocked on HTML'), ('bm', 'Blocked on Mock'), ('nn', 'Not Needed'), ('ns', 'Next Sprint'), ('dp', 'Duplicate'), ('cr', 'CR')], default='Status', max_length=20),
        ),
    ]
