# Generated by Django 2.2 on 2019-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0080_remove_user_detail_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='display_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='Profile')),
                ('user_id', models.IntegerField(blank='False')),
            ],
        ),
    ]
