# Generated by Django 2.2 on 2019-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0081_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_picture',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
