# Generated by Django 2.1.7 on 2019-07-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0082_auto_20190702_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
    ]
