# Generated by Django 2.2 on 2019-08-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0082_auto_20190819_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_picture',
            old_name='user_id',
            new_name='idx',
        ),
    ]
