# Generated by Django 2.1.7 on 2019-07-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0083_remove_story_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='prg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('pdate', models.DateField()),
                ('jprg', models.CharField(max_length=15)),
                ('pprg', models.CharField(max_length=15)),
                ('hprg', models.CharField(max_length=15)),
                ('qprg', models.CharField(max_length=15)),
                ('s_name', models.CharField(max_length=200)),
            ],
        ),
    ]
