# Generated by Django 2.2 on 2019-08-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0083_auto_20190819_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='profile_picture',
        ),
    ]
