# Generated by Django 2.1.7 on 2019-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0084_prg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg',
            name='s_name',
        ),
        migrations.AddField(
            model_name='prg',
            name='jd',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
