# Generated by Django 2.2 on 2019-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0085_auto_20190820_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_details',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
