# Generated by Django 2.1.7 on 2019-07-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0086_auto_20190703_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prg',
            name='qprg',
        ),
    ]
