# Generated by Django 2.2 on 2019-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0087_remove_story_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_details',
            name='change_date',
            field=models.DateField(blank='False', default=None),
        ),
    ]
