# Generated by Django 2.1.7 on 2019-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0087_remove_prg_qprg'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg',
            name='qprg',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
