# Generated by Django 2.1.7 on 2019-07-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0088_prg_qprg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prg',
            name='qprg',
            field=models.CharField(max_length=15),
        ),
    ]
