# Generated by Django 2.2 on 2019-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0089_remove_story_details_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_details',
            name='change_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
