# Generated by Django 2.1.7 on 2019-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0089_auto_20190703_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prg',
            old_name='pdate',
            new_name='edate',
        ),
        migrations.RenameField(
            model_name='prg',
            old_name='hprg',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='prg',
            name='jprg',
        ),
        migrations.RemoveField(
            model_name='prg',
            name='pprg',
        ),
        migrations.RemoveField(
            model_name='prg',
            name='qprg',
        ),
        migrations.AddField(
            model_name='prg',
            name='dname',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prg',
            name='sdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
