# Generated by Django 2.1.7 on 2019-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0090_auto_20190703_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg',
            name='days',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
