# Generated by Django 2.2 on 2019-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0091_remove_story_details_change_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_picture',
            old_name='idx',
            new_name='idx1',
        ),
    ]
