# Generated by Django 2.1.7 on 2019-07-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0092_register_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='uname',
        ),
    ]
