# Generated by Django 2.2 on 2019-08-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0092_auto_20190826_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_picture',
            old_name='idx1',
            new_name='idx',
        ),
    ]
