# Generated by Django 2.1.7 on 2019-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0093_remove_register_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='uname',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
